# Generated by Django 4.1 on 2022-10-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
