# Generated by Django 4.1 on 2022-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_money_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
